import turtle
turtle.speed(50)
turtle.showturtle()
turtle.bgcolor('blue')
turtle.pencolor('white')
def star_7():

    angle = 180.0 - 180.0 / 7
    turtle.fillcolor('white')
    turtle.begin_fill()
    for x in range (7):
        turtle.forward(40)
        turtle.right(angle)
    turtle.end_fill()

def star_7_large():

    angle = 180.0 - 180.0 / 7
    turtle.fillcolor('white')
    turtle.begin_fill()
    for x in range (7):
        turtle.forward(100)
        turtle.right(angle)
    turtle.end_fill()

def star_5():
    angle = 180.0 - 180.0 / 5
    turtle.fillcolor('white')
    turtle.begin_fill()
    for x in range (5):
        turtle.forward(20)
        turtle.right(angle)
    turtle.end_fill()

def white_cross():
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(90)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(150)
    turtle.left(135)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(130)
    turtle.left(135)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(90)
    turtle.left(135)
    turtle.forward(130)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(140)
    turtle.left(135)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(130)
    turtle.left(135)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(30)
    turtle.end_fill()
    turtle.penup()

def red_cross():
    turtle.fillcolor('red')
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(90)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(150)
    turtle.left(135)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(130)
    turtle.left(135)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(90)
    turtle.left(135)
    turtle.forward(130)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(140)
    turtle.left(135)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(130)
    turtle.left(135)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(10)
    turtle.end_fill()
    turtle.penup()





turtle.penup()
turtle.right(180)
turtle.goto(100,-30)
turtle.pendown()
star_7()
turtle.penup()
turtle.goto(150,60)
turtle.pendown()
star_7()
turtle.penup()
turtle.goto(150,-200)
turtle.pendown()
star_7()
turtle.penup()
turtle.goto(250,-20)
turtle.pendown()
star_7()
turtle.penup()
turtle.goto(200,-50)
turtle.pendown()
star_5()
turtle.penup()
turtle.goto(-120,-160)
turtle.pendown()
star_7_large()
turtle.penup()
turtle.goto(-120,180)
turtle.pendown()
white_cross()
turtle.penup()
turtle.goto(-125,150)
turtle.pendown
red_cross()

turtle.done()
